<? $this->inlineScript()->captureStart() ?>
    function deleteMessage(mid){

		ajax_request('/index/deletemessage/', {'mess_id': mid }, '<?= Vida_Helpers_Text::_T('messdeletemessage') ?>',
						function(responseText) {
							Effect.DropOut('message_'+mid);

							var current_count_messages = $('hiddencountmessages').innerHTML-1;
							if(current_count_messages <= 0){ $('zerromassages').innerHTML = '<?= Vida_Helpers_Text::_T('zerromassages') ?>'; }

							$('hiddencountmessages').innerHTML = $('hiddencountmessages').innerHTML-1;
						}
					);
                    
	}
<? $this->inlineScript()->captureEnd() ?>

<div class="search_results_container">
	<h1><?= Vida_Helpers_Text::_T('mymessages') ?></h1>
        <?= $this->MyMessages(); ?>
</div>