<? $this->inlineScript()->captureStart() ?>
//var values = {'login': 'проверка', 'email': 'test@gmail.com', 'password': '', 'conf_password': '', 'bdate': 2, 'bmonth': 2, 'byear': 1977, 'sex': 1};
var values = <?= $this->values ?>;
var errors = <?= $this->errors ?>;
values.password = "";
values.conf_password = "";
var profile_loaded = false;
document.observe('dom:loaded', function() {
    if(profile_loaded) return false;
    profile_loaded = true;
    keydown_ex('profile-form', profile_submit);
    populate_values('profile-form', values);
    populate_errors(errors);
    if(errors.conf_password != null || errors.password != null) {
        invert('password-container');
    }
});

function invert(el) {
    el = $(el);
    if(el.visible()) {
       el.hide(); 
    } else {
        el.show(); 
    }
}

function profile_submit() {
   // alert('submit');
}

<? $this->inlineScript()->captureEnd() ?>
<?= $this->inlineScript() ?>

<form id="profile-form" method="POST" action="/pspace/profile/" name="profile">
<div class="upload_video_container">
<h1><?= Vida_Helpers_Text::_T('Ваша учетная запись') ?></h1>
<div class="register">

<div class="field_name"><?= Vida_Helpers_Text::_T('Имя (ник)') ?>:</div>
<input type="text" disabled name="username" />

<div class="field_name">Email:</div>
<div class="reg_errormsg" id="email_error"></div>
<input type="text" name="email"/>

<div class="change_password"><a href="javascript:void(0);" onclick="invert('password-container')"><?= Vida_Helpers_Text::_T('Изменить пароль') ?></a></div>
<div id="password-container" style="display:none">
<div class="field_name"><?= Vida_Helpers_Text::_T('Новый пароль') ?>:</div>
<div class="reg_errormsg" id="password_error"></div>
<input type="password" name="password" />

<div class="field_name"><?= Vida_Helpers_Text::_T('Подтвердите пароль') ?>:</div>
<div class="reg_errormsg" id="conf_password_error"></div>
<input type="password" name="conf_password"/>
</div>
<div class="field_name"><?= Vida_Helpers_Text::_T('Дата рождения') ?>:</div>
<div class="reg_errormsg" id="birthdate_error"></div>
<div class="birth_date">
<select name="bday">
    <option disabled selected><?= Vida_Helpers_Text::_T('День') ?></option>
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
    <option value="4">4</option>
    <option value="5">5</option>
    <option value="6">6</option>
    <option value="7">7</option>
    <option value="8">8</option>
    <option value="9">9</option>
    <option value="10">10</option>
    <option value="11">11</option>
    <option value="12">12</option>
    <option value="13">13</option>
    <option value="14">14</option>
    <option value="15">15</option>
    <option value="16">16</option>
    <option value="17">17</option>
    <option value="18">18</option>
    <option value="19">19</option>
    <option value="20">20</option>
    <option value="21">21</option>
    <option value="22">22</option>
    <option value="23">23</option>
    <option value="24">24</option>
    <option value="25">25</option>
    <option value="26">26</option>
    <option value="27">27</option>
    <option value="28">28</option>
    <option value="29">29</option>
    <option value="30">30</option>
    <option value="31">31</option>
</select>
<select name="bmonth">
    <option disabled selected><?= Vida_Helpers_Text::_T('Месяц') ?></option>
    <option value="0"><?= Vida_Helpers_Text::_T('Январь') ?></option>
    <option value="1"><?= Vida_Helpers_Text::_T('Февраль') ?></option>
    <option value="2"><?= Vida_Helpers_Text::_T('Март') ?></option>
    <option value="3"><?= Vida_Helpers_Text::_T('Апрель') ?></option>
    <option value="4"><?= Vida_Helpers_Text::_T('Май') ?></option>
    <option value="5"><?= Vida_Helpers_Text::_T('Июнь') ?></option>
    <option value="6"><?= Vida_Helpers_Text::_T('Июль') ?></option>
    <option value="7"><?= Vida_Helpers_Text::_T('Август') ?></option>
    <option value="8"><?= Vida_Helpers_Text::_T('Сентябрь') ?></option>
    <option value="9"><?= Vida_Helpers_Text::_T('Октябрь') ?></option>
    <option value="10"><?= Vida_Helpers_Text::_T('Ноябрь') ?></option>
    <option value="11"><?= Vida_Helpers_Text::_T('Декабрь') ?></option>
</select>
<select name="byear">
<option disabled selected><?= Vida_Helpers_Text::_T('Год') ?></option>
    <option value="1939">1939</option>
    <option value="1940">1940</option>
    <option value="1941">1941</option>
    <option value="1942">1942</option>
    <option value="1943">1943</option>
    <option value="1944">1944</option>
    <option value="1945">1945</option>
    <option value="1946">1946</option>
    <option value="1947">1947</option>
    <option value="1948">1948</option>
    <option value="1949">1949</option>
    <option value="1950">1950</option>
    <option value="1951">1951</option>
    <option value="1952">1952</option>
    <option value="1953">1953</option>
    <option value="1954">1954</option>
    <option value="1955">1955</option>
    <option value="1956">1956</option>
    <option value="1957">1957</option>
    <option value="1958">1958</option>
    <option value="1959">1959</option>
    <option value="1960">1960</option>
    <option value="1961">1961</option>
    <option value="1962">1962</option>
    <option value="1963">1963</option>
    <option value="1964">1964</option>
    <option value="1965">1965</option>
    <option value="1966">1966</option>
    <option value="1967">1967</option>
    <option value="1968">1968</option>
    <option value="1969">1969</option>
    <option value="1970">1970</option>
    <option value="1971">1971</option>
    <option value="1972">1972</option>
    <option value="1973">1973</option>
    <option value="1974">1974</option>
    <option value="1975">1975</option>
    <option value="1976">1976</option>
    <option value="1977">1977</option>
    <option value="1978">1978</option>
    <option value="1979">1979</option>
    <option value="1980">1980</option>
    <option value="1981">1981</option>
    <option value="1982">1982</option>
    <option value="1983">1983</option>
    <option value="1984">1984</option>
    <option value="1985">1985</option>
    <option value="1986">1986</option>
    <option value="1987">1987</option>
    <option value="1988">1988</option>
    <option value="1989">1989</option>
    <option value="1990">1990</option>
    <option value="1991">1991</option>
    <option value="1992">1992</option>
    <option value="1993">1993</option>
    <option value="1994">1994</option>
    <option value="1995">1995</option>
    <option value="1996">1996</option>
    <option value="1997">1997</option>
    <option value="1998">1998</option>
    <option value="1999">1999</option>
    <option value="2000">2000</option>
    <option value="2001">2001</option>
    <option value="2002">2002</option>
    <option value="2003">2003</option>
    <option value="2004">2004</option>
    <option value="2005">2005</option>
    <option value="2006">2006</option>
    <option value="2007">2007</option>
    <option value="2008">2008</option>
    <option value="2009">2009</option>  
</select>
</div>

<div class="field_name"><?= Vida_Helpers_Text::_T('Ваш пол') ?>:</div>
<select name="sex" class="gender">
<option value="1"><?= Vida_Helpers_Text::_T('Мужской') ?></option>
<option value="0"><?= Vida_Helpers_Text::_T('Женский') ?></option>
</select>

<input type="image" src="/images/prof_edit_<?= Vida_Helpers_Text::_L() ?>.gif" onclick="profile_submit()" class="edit_profile" />

</div>
</div>

</form>