<div class="workpage2">
<h1>Placement File</h1>

These rules describe the conditions of service site video.ukr.ua (hereinafter "we"), you (hereinafter "you", "User"). Using video.ukr.ua you automatically agree with the following conditions:
<br /><br />
<b>1. Ownership</b>
All materials on the site (except those that were provided to users) are owned video.ukr.ua. This includes: design, logos, sounds, software - all together "Materials". All materials are protected by copyright law and may not be partially or fully utilized without the prior written consent of the video.ukr.ua.
<br /><br />
<b>2. Contact information user</b>
The user undertakes to provide full, accurate and up-to-date contact information. In the event of a failure to communicate with the user by providing them with contact information, access to the files that the user may be temporarily suspended.
<br /><br />
<b>3. Using e-mail addresses of users</b>
Sometimes video.ukr.ua may make deliveries to their customers with notices of important changes in the site or legal basis. By giving us your e-mail address you agree to receive these mailings. For our part, we garantruem that send information will be strictly informational and in no way an advertising nature will be strictly limited in quantity.
<br /><br />
<b>4. The use of</b>
<br /><br />
<b>4.1. The contents of files</b>
<br /><br />
Is categorically not allowed to download files of erotic and pornographic nature, promoting violence, racial or national intolerance, containing viruses, trojans and other malicious programs.
<br /><br />
<b>4.2. Claims of rights</b>
video.ukr.ua does not reflect the nature of information that is transmitted using our services. At the same time, we adhere to a strict policy antipiratstva. In case (on its own or upon application of a legal right) files with illegal or prohibited by current legislation, the content, they will be immediately removed without warning. Also video.ukr.ua reserves the right to block access to their services to users who have been repeatedly observed in the dissemination of illegal material. In the case of any public authorities in the ongoing investigation regarding the illegal dissemination of information, video.ukr.ua will do everything possible to promote such investigations by the appropriate authorities with all available information about the user, including e-mail, ip address, and any other required information.<br />
</div>
