<div class="search_results_container">
<h1><?= Vida_Helpers_Text::_T('Файлы категории') ?> "<?= $this->category ?>"</h1>
<div style="clear: both"></div>
<h2><?= Vida_Helpers_Text::_T('Найдено роликов') ?>: <?= $this->count ?></h2>

<!--div class="s_r_sort">123</div-->

<?php if (count($this->paginator)): ?>
    <?= $this->paginator; ?>
    <?php foreach ($this->entries as $file): ?>
        <?= $this->videoItem($file) ?>
    <?php endforeach; ?>
    <?= $this->paginator; ?>
<?php else: ?>
        <p><?= Vida_Helpers_Text::_T('Не найдено ни одного ролика') ?></p>
<?php endif ?>

</div>
