<div class="categories">

	<div class="categories_header">
		<div class="header_img"></div>
			<h1><?= Vida_Helpers_Text::_T('allcategory') ?></h1>
	</div>

	<table class="block categories_list">
		<thead>
			<tr><td><b></b></td></tr>
		</thead>
		<tr>
			<td class="block_middle">
				<div class="block_container">
					<div class="categories_links">
						<?= $this->category_uploaded_file ?>
					</div>
				</div>
				<i></i>
			</td>
		</tr>
		<tr>
			<th><i></i></th>
		</tr>
	</table>

</div>
